development:
  adapter: mysql2
  encoding: utf8
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] %>
  database: ultrasound_development
test:
  adapter: mysql2
  encoding: utf8
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] %>
  database: ultrasound_test
production:
  adapter: mysql2
  encoding: utf8
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] %>
  database: ultrasound_production
